### ISSUE TITLE
Character.TotalDamage

### ISSUE THREAD

**Issue by D34THcz** [D34THcz/Game#2]
Character.TotalDamage (má značit celkový způsobitelný Damage, teď je to součet Character.BaseDamage + Character.EquipedWeapon.DamageModifier) - nyní se aktualizuje po nasazení nebo sundání
zbraně z characteru. Výpočet TotalDamage by asi měl být přímo ve třídě Characteru místo třídy EquipableWeapon

**Comment by D34THcz** [comment]
Character.TotalDamage přepočítat vždy při EquipItem(), UnEquipItem(). Nebo při každém útoku přepočítat staty z postavy a itemů na postavě.

**Comment by D34THcz** [comment]
_TotalDamage = BaseDamage + EquipedWeapon.DamageModifier ?? 0_

**Comment by D34THcz** [comment]
Implementace metody `RefreshTotalDamage()` ve třídě `Character`. Metoda přepočítá `Character.TotalDamage` (bere v potaz jestli je nasazena zbraň). Metoda se zavolá po nasazení nebo sundání zbraně a volá se i v setteru pro `Character.TotalDamage`.

**Comment by D34THcz** [comment]
Pokud na začátku programu není equipnuta zbraň, je `TotalDamage` 0

**Comment by mystyo** [comment]
Vypocet bych videl asi takhle. Pseudo kod, promene nemusi odpovidat skutecnosti

```
void DealDamage(Character target){
   var amount = CalculateTotalDamage();
   target.ReceiveDamage(amount);
}

int CalculateTotalDamage() {
   int totalDamage = 0;
   int strength = 0;
   // Get base damage of weapon
   totalDamage = EquipedWeapon.Damage;
   
   // Get character strength that modify damage
  foreach( item in EquipedItems){
      strength += item.Strength;
   }
 
   // Apply strength modifier 
   totalDamage = totalDamage * (1 + strength / 100);
   
   return totalDamage;
}
```

**Comment by D34THcz** [comment]
> ```
>    // Get character strength that modify damage
>   foreach( item in EquipedItems){
>       strength += item.Strength;
>    }
>  
> ```

Jaké by bylo idealní řešení pro proměnnou `EquipedItems`?
Napadá me array s referencí na equipnuté itemy, protože to bude pevně daný počet "slotů" na postavě. Šel by použít i List nebo jiná kolekce. Ale nejsem si jistý, jestli je správné, že by se pak do všech metod pro nasazování/sundavani itemů na postavu, itemy přiřazovali do EquipedWeapon,  EquipedArmor atd. a pak ještě do další proměnné, třeba toho pole.
Ještě mě napadlo, že by se dala vytvořit nová třída, podobná inventáři, ale řešila by tyto sloty na postavě.

**Comment by mystyo** [comment]
Když si vezmu jak funguje nějaké RPG. Tak obvykle každý slot má svůj typ. 

Takže bych to viděl na nějakou `Dictionary<ItemType, Item>` To bys měl ale jeden unikatní item typ na postavu, nefungovalo by to moc dobře pokud bys chtěl mít třeba 2 prsteny. 

Takže možná lepší varianta by byla `Dictionary<Slot, Item>` Jen bys někde musel ošetřit to, abys nemohl do slotu na helmu dát třeba ring etc.

**Comment by D34THcz** [comment]
Tak tady jsem skončil :( tu první variantu s Dictionary<ItemType, Item> bych asi zvládnul, ale několik dní už špekuluju jak vyřešit tu druhou variantu pro více slotů stejného typu. Implementaci samotného Slotu. Zkoušel jsem Enumy s typy výbavy, zkoušel jsem vytvořit zvlášť třídu Slot a nevím si s tím rady. Jedno řešení fungovalo tak napůl, ale bylo tam strašně moc podmínkování, když došlo právě na sloty stejného typu. Takže to neberu za validní řešení. Asi budu potřebovat trochu nasměrovat prosím :)

**Comment by D34THcz** [comment]
Tak nakonec jsem to dal nějak dohromady, vypadá to i funkčně, ale myslím si, že až to uvidíš, tak už se mnou nebudeš chtít mít cokoliv společného :D
A taky je tam bug, v programu se používá metoda EquipGear pro nasazování předmětů na postavu a jako jeden z parametrů je slot, do kterého se item má nasadit, ale jde tam napsat slot jiné postavy a to by určitě jít nemělo.

**Comment by mystyo** [comment]
Začal si to mít zbytečně moc složité, podívej se na to co bych navrhnul já. Napsal jsem to fakt rychle tak tam není všechno a můžou tam být chyby .

https://github.com/D34THcz/Game/pull/8

Nemusíš to podle toho přepisovat jen to vem jako inspiraci, abys to neměl zbytečně složité.
Co se týče equipu stejného item typu 2x (např. ring) tak tohle tam chybí naimplementovat, udělal bych to asi if statementem kdy ring type má id 4 tak by mohl zabrat sloty 4 a 5 jestli mě chápeš.
