### ISSUE TITLE
Cross referencing

### ISSUE THREAD

**Issue by D34THcz** [D34THcz/Game#4]
Nedržet na Weapon referenci na Character ani Inventory. Item nepotřebuje vědět kde se nachází.

**Comment by D34THcz** [comment]
Po zrušení referencí na `Character` a `Inventory` ve třídě `EquipableWeapon`, vznikl problém - metoda `EquipItem()` používala referenci na `Character` a její `Inventory` - v metodě se přiřazovala zbraň k postavě: `Character. EquipedWeapon = this` a `Character.Inventory.Items.Remove = this`.

Napadli mě dvě řešení (mě se více líbí to druhé):
- zrušit metody `EquipItem()` a `UnEquipItem()` ve třídě `Equipable` a ručně přiřazovat v programu: `player.EquipedWeapon = player.Inventory.Item(vybrat item z listu);` a adekvátní řešení pro metodu `UnEquipItem()`
- upravit metodu `EquipItem()` ve třídě `EquipableWeapon` přidáním parametru - `EquipItem(Character character){ character.EquipedWeapon = this; character.Inventory.Items.Remove(this); }` a adekvátní řešení pro metodu `UnEquipItem()`

**Comment by mystyo** [comment]
`[Une|E]quipWeapon()` bych rozhodne dal na Charakter, protoze kdyz si to vezmes i z logickeho hlediska, ty jakozto postava ten predmet vezmes do ruky/na sebe. 

To ze si to jednou takhle navrhnul na UML neznamena notne, ze to tak musi byt, kdyz te pak napadne lepsi reseni. Ja teda preferuju pragmaticky pristup, nez nejake dogmata. 

`UseItem()` bude trosku jiny, ten by mel byt i na Characteru i na Itemu, jelikoz kdyz jako postava pouzijes ten item, tak ten item by mel mit nejakou vnitrni logiku co vlastne udela a tohle bych neimplementoval do Characteru.

**Comment by mystyo** [comment]
Takze zkus to naimplementovat tak, aby `EquipItem()` byl na te postave.

**Comment by D34THcz** [comment]
Implementoval jsem tedy `[Une|E]quipWeapon()` a `UseItem()` na Character. `UseItem()` na Characteru teď vypadá takto
 ```
public void UseItem(Item item)
{
       item.UseItem(this);
}
```
a následně už má každý Item svou vlastní logiku, kde může pracovat s characterem, který mu tato metoda pošle.
Metodu pro zničení/spotřebování itemu jsem vyřešil tak, že se item odebere z inventáře characteru.
